### ISSUE TITLE
Unable to build - wrong toolchain

### ISSUE THREAD

**Issue by sarbyn** [jfvelte-dev/android_device_samsung_jfvelte#1]
This is not a real issue, but only a notice about a strange behaviour.
After a clean repo sync I'm unable to build using your BoardConfigCommon.mk and I have to patch it with this 
[patch](https://github.com/sarbyn/android_device_samsung_jf-common/commit/df2bff25d57563ced57728e9da70cd3535234883)
My question is: why there is a mismatch with toolchain and recovery image size? 
Is it possible that your build environment is outdated or is based on an old configuration (maybe for CM 12.1) and needs a fix?

Ups...I've forgot the most important thing: great work guys!

**Comment by sombree** [comment]
It's not mismatch between toolchain and recovery size. It's because kernel is build with -O2 flag (you can find it in Makefile in kernel rootdir, just search file for word "optimize"). Personally i've simply copied value of BOARD_SYSTEMIMAGE_PARTITION_SIZE to BOARD_RECOVERYIMAGE_PARTITION_SIZE.
On the other hand if you want to be able to use that recovery simply change flag from -O2 to -Os
:)

**Comment by sarbyn** [comment]
And what about the toolchain name? With a clean repo sync I can't find the arm-eabi-xxxx but only the arm-linux-androideabi-xxx

```
-KERNEL_TOOLCHAIN := $(ANDROID_BUILD_TOP)/prebuilts/gcc/$(HOST_OS)-x86/arm/arm-eabi-4.9/bin
-KERNEL_TOOLCHAIN_PREFIX := arm-eabi-
+KERNEL_TOOLCHAIN := $(ANDROID_BUILD_TOP)/prebuilts/gcc/$(HOST_OS)-x86/arm/arm-linux-androideabi-4.9/bin
+KERNEL_TOOLCHAIN_PREFIX := arm-linux-androideabi-
```

**Comment by sombree** [comment]
You can try arm-linux-androideabi to build kernel or simply manualy download and put some arm-eabi toolchain there :)
